spring.application.name=OnTap_SOF3022
# --KET_NOI CSDL--
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=sof3021_jpa_tren_lop;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=YourPassword!123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
# --JPA--
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
